name: agrinix
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  go_router: ^13.2.0
  glassmorphism_ui: ^0.3.0
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  riverpod: ^2.6.1
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  geolocator: ^14.0.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/capture-crop.jpg
    - assets/images/crop-image.jpg
    - assets/images/diagnosis.jpg
    - assets/images/register-image.jpg
    - assets/images/treat-crop.jpg
    - assets/images/farmer-login.jpg
    - assets/images/google-logo.png
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/static/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/static/Nunito-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Nunito/static/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/static/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/static/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/static/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/static/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/static/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Roboto/static/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/static/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/static/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/static/Inter_18pt-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Inter/static/Inter_18pt-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Cormorant Garamond
      fonts:
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-Light.ttf
          weight: 300
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Libre Baskerville
      fonts:
        - asset: assets/fonts/Libre_Baskerville/LibreBaskerville-Regular.ttf
          weight: 400
        - asset: assets/fonts/Libre_Baskerville/LibreBaskerville-Bold.ttf
          weight: 700
        - asset: assets/fonts/Libre_Baskerville/LibreBaskerville-Italic.ttf
          style: italic
          weight: 400
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Tektur
      fonts:
        - asset: assets/fonts/Tektur/static/Tektur-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tektur/static/Tektur-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tektur/static/Tektur-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Tektur/static/Tektur-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tektur/static/Tektur-Black.ttf
          weight: 900
        - asset: assets/fonts/Tektur/static/Tektur_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tektur/static/Tektur_Condensed-Bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
