import 'package:flutter/material.dart';

final ThemeData appTheme = ThemeData(
  useMaterial3: true,
  primaryColor: Color(0xFF4CAF50),
  scaffoldBackgroundColor: Color(0xFFf1f8e9),
  colorScheme: ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF4CAF50),
    onPrimary: Color(0xFF272624),
    secondary: Color(0xFFffeb3b),
    onSecondary: Color(0xFF272624),
    error: Color(0xFFe53935),
    onError: Color(0xFF272624),
    surface: Color(0xFFf1f8e9),
    onSurface: Color(0xFF272624),
  ),
  textTheme: TextTheme(
    displayLarge: TextStyle(
      fontFamily: 'Cormorant Garamond',
      fontWeight: FontWeight.bold,
      fontSize: 48,
      color: Color(0xFF272624),
      letterSpacing: 0.5,
    ),
    displayMedium: TextStyle(
      fontFamily: 'Cormorant Garamond',
      fontWeight: FontWeight.w600,
      fontSize: 40,
      color: Color(0xFF272624),
      letterSpacing: 0.25,
    ),
    displaySmall: TextStyle(
      fontFamily: 'Cormorant Garamond',
      fontWeight: FontWeight.w500,
      fontSize: 32,
      color: Color(0xFF272624),
    ),
    headlineLarge: TextStyle(
      fontFamily: 'Cormorant Garamond',
      fontWeight: FontWeight.w600,
      fontSize: 28,
      color: Color(0xFF272624),
    ),
    headlineMedium: TextStyle(
      fontFamily: 'Cormorant Garamond',
      fontWeight: FontWeight.w500,
      fontSize: 24,
      color: Color(0xFF272624),
    ),
    headlineSmall: TextStyle(
      fontFamily: 'Cormorant Garamond',
      fontWeight: FontWeight.w400,
      fontSize: 20,
      color: Color(0xFF272624),
    ),
    titleLarge: TextStyle(
      fontFamily: 'Nunito',
      fontWeight: FontWeight.w700,
      fontSize: 20,
      color: Color(0xFF272624),
    ),
    titleMedium: TextStyle(
      fontFamily: 'Nunito',
      fontWeight: FontWeight.w600,
      fontSize: 18,
      color: Color(0xFF272624),
    ),
    titleSmall: TextStyle(
      fontFamily: 'Nunito',
      fontWeight: FontWeight.w500,
      fontSize: 16,
      color: Color(0xFF272624),
    ),
    bodyLarge: TextStyle(
      fontFamily: 'Nunito',
      fontWeight: FontWeight.w400,
      fontSize: 16,
      color: Color(0xFF272624),
    ),
    bodyMedium: TextStyle(
      fontFamily: 'Nunito',
      fontWeight: FontWeight.w400,
      fontSize: 14,
      color: Color(0xFF272624),
    ),
    bodySmall: TextStyle(
      fontFamily: 'Nunito',
      fontWeight: FontWeight.w300,
      fontSize: 12,
      color: Color(0xFF272624),
    ),
    labelLarge: TextStyle(
      fontFamily: 'Inter',
      fontWeight: FontWeight.w600,
      fontSize: 14,
      color: Color(0xFF4CAF50),
      letterSpacing: 0.5,
    ),
    labelMedium: TextStyle(
      fontFamily: 'Inter',
      fontWeight: FontWeight.w500,
      fontSize: 12,
      color: Color(0xFF4CAF50),
      letterSpacing: 0.5,
    ),
    labelSmall: TextStyle(
      fontFamily: 'Inter',
      fontWeight: FontWeight.w400,
      fontSize: 10,
      color: Color(0xFF4CAF50),
      letterSpacing: 0.5,
    ),
  ),
  datePickerTheme: DatePickerThemeData(),
);
